### PR TITLE
link to notevil

### PR DESCRIPTION
**Pull request by dominictarr**
This is a javascript interpreter implemented _in javascript_. I think that definately passes the threashold for _mad science_.

### CODE REVIEW

**Comment by feross** [comment]
wow, incredible stuff

**Comment by feross** [comment]
btw, I assume you meant https://www.npmjs.com/package/notevil, right?

**Comment by dominictarr** [comment]
oh yeah

**Comment by dominictarr** [comment]
haha, oops! c/p fail.

**Pull request merged**
